---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: enterprise-gateway-pvc
  labels:
    app: enterprise-gateway
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30G
  selector:
    matchLabels:
      app: enterprise-gateway
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kernelspecs-pvc
  labels:
    app: enterprise-gateway
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10G
  selector:
    matchLabels:
      app: enterprise-gateway
