apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../72_kubeflow/kf110/.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/cert-manager-kube-system-resources
