apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: www
  creationTimestamp: null
  labels:
    name: dash
  name: dash
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: dash
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dash
    spec:
      containers:
      - image: binderhubonline/dash:1.0.3
        name: dash
        imagePullPolicy: Always
        ports:
        - containerPort: 8050
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
