---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: jupyterbook
  name: jupyterhub-shared-pvc
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
   requests:
    storage: 30G
