apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"katib","app.kubernetes.io/component":"katib","app.kubernetes.io/instance":"katib-controller-0.8.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"katib-controller","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.8.0","component":"mysql"},"name":"katib-mysql","namespace":"kubeflow"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"katib","app.kubernetes.io/component":"katib","app.kubernetes.io/instance":"katib-controller-0.8.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"katib-controller","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.8.0","component":"mysql"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"labels":{"app":"katib","app.kubernetes.io/component":"katib","app.kubernetes.io/instance":"katib-controller-0.8.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"katib-controller","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.8.0","component":"mysql"},"name":"katib-mysql"},"spec":{"containers":[{"args":["--datadir","/var/lib/mysql/datadir"],"env":[{"name":"MYSQL_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"MYSQL_ROOT_PASSWORD","name":"katib-mysql-secrets"}}},{"name":"MYSQL_ALLOW_EMPTY_PASSWORD","value":"true"},{"name":"MYSQL_DATABASE","value":"katib"}],"image":"mysql:8","livenessProbe":{"exec":{"command":["/bin/bash","-c","mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"]},"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":5},"name":"katib-mysql","ports":[{"containerPort":3306,"name":"dbapi"}],"readinessProbe":{"exec":{"command":["/bin/bash","-c","mysql -D ${MYSQL_DATABASE} -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"]},"initialDelaySeconds":5,"periodSeconds":10,"timeoutSeconds":1},"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"katib-mysql"}]}],"volumes":[{"name":"katib-mysql","persistentVolumeClaim":{"claimName":"katib-mysql"}}]}}}}
  creationTimestamp: "2020-11-09T03:06:19Z"
  generation: 1
  labels:
    app: katib
    app.kubernetes.io/component: katib
    app.kubernetes.io/instance: katib-controller-0.8.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: katib-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.8.0
    component: mysql
  name: katib-mysql
  namespace: kubeflow
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: false
    kind: Application
    name: katib-controller
    uid: 40cd9b1f-c44b-4040-8104-ce5eec87464a
  resourceVersion: "4871"
  selfLink: /apis/apps/v1/namespaces/kubeflow/deployments/katib-mysql
  uid: b6c98502-008d-4634-be04-6707de3b79f4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: katib
      app.kubernetes.io/component: katib
      app.kubernetes.io/instance: katib-controller-0.8.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: katib-controller
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.8.0
      component: mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: katib
        app.kubernetes.io/component: katib
        app.kubernetes.io/instance: katib-controller-0.8.0
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: katib-controller
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: 0.8.0
        component: mysql
      name: katib-mysql
    spec:
      containers:
      - args:
        - --datadir
        - /var/lib/mysql/datadir
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: katib-mysql-secrets
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: katib
        image: mysql:8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: katib-mysql
        ports:
        - containerPort: 3306
          name: dbapi
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mysql -D ${MYSQL_DATABASE} -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT
              1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: katib-mysql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: katib-mysql
        persistentVolumeClaim:
          claimName: katib-mysql
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-09T03:06:50Z"
    lastUpdateTime: "2020-11-09T03:06:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-11-09T03:06:19Z"
    lastUpdateTime: "2020-11-09T03:06:50Z"
    message: ReplicaSet "katib-mysql-74747879d7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
