apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"metadata","app.kubernetes.io/instance":"metadata-0.2.1","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"metadata","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.1","component":"db","kustomize.component":"metadata"},"name":"metadata-db","namespace":"kubeflow"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/component":"metadata","app.kubernetes.io/instance":"metadata-0.2.1","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"metadata","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.1","component":"db","kustomize.component":"metadata"}},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"metadata","app.kubernetes.io/instance":"metadata-0.2.1","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"metadata","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.1","component":"db","kustomize.component":"metadata"},"name":"db"},"spec":{"containers":[{"args":["--datadir","/var/lib/mysql/datadir"],"envFrom":[{"configMapRef":{"name":"metadata-db-parameters"}},{"secretRef":{"name":"metadata-db-secrets"}}],"image":"mysql:8.0.3","name":"db-container","ports":[{"containerPort":3306,"name":"dbapi"}],"readinessProbe":{"exec":{"command":["/bin/bash","-c","mysql -D $$MYSQL_DATABASE -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]},"initialDelaySeconds":5,"periodSeconds":2,"timeoutSeconds":1},"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"metadata-mysql"}]}],"volumes":[{"name":"metadata-mysql","persistentVolumeClaim":{"claimName":"metadata-mysql"}}]}}}}
  creationTimestamp: "2020-11-09T03:06:13Z"
  generation: 1
  labels:
    app.kubernetes.io/component: metadata
    app.kubernetes.io/instance: metadata-0.2.1
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: metadata
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.2.1
    component: db
    kustomize.component: metadata
  name: metadata-db
  namespace: kubeflow
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: false
    kind: Application
    name: metadata
    uid: e3ce0d6d-9243-44a3-a02b-37353995df85
  resourceVersion: "5061"
  selfLink: /apis/apps/v1/namespaces/kubeflow/deployments/metadata-db
  uid: 9c3708ce-be56-49d5-9136-54b77b3d240e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: metadata
      app.kubernetes.io/instance: metadata-0.2.1
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: metadata
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.2.1
      component: db
      kustomize.component: metadata
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: metadata
        app.kubernetes.io/instance: metadata-0.2.1
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: metadata
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: 0.2.1
        component: db
        kustomize.component: metadata
      name: db
    spec:
      containers:
      - args:
        - --datadir
        - /var/lib/mysql/datadir
        envFrom:
        - configMapRef:
            name: metadata-db-parameters
        - secretRef:
            name: metadata-db-secrets
        image: mysql:8.0.3
        imagePullPolicy: IfNotPresent
        name: db-container
        ports:
        - containerPort: 3306
          name: dbapi
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mysql -D $$MYSQL_DATABASE -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: metadata-mysql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: metadata-mysql
        persistentVolumeClaim:
          claimName: metadata-mysql
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-09T03:07:11Z"
    lastUpdateTime: "2020-11-09T03:07:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-11-09T03:06:13Z"
    lastUpdateTime: "2020-11-09T03:07:11Z"
    message: ReplicaSet "metadata-db-79d6cf9d94" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
