apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2020-11-08T15:28:15Z","generation":1,"labels":{"app":"tensorboard","kustomize.component":"tensorboard"},"name":"tensorboard","namespace":"kubeflow","resourceVersion":"10028","selfLink":"/apis/extensions/v1beta1/namespaces/kubeflow/deployments/tensorboard","uid":"17a76a46-4647-4b1e-92b9-3fdc88072a28"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"kustomize.component":"tensorboard"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"tensorboard","kustomize.component":"tensorboard"}},"spec":{"containers":[{"args":["--logdir=logs","--port=6006"],"command":["/usr/local/bin/tensorboard"],"image":"tensorflow/tensorflow:1.8.0","imagePullPolicy":"IfNotPresent","name":"tensorboard","ports":[{"containerPort":6006,"protocol":"TCP"}],"resources":{"limits":{"cpu":"4","memory":"4Gi"},"requests":{"cpu":"1","memory":"1Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-11-08T15:29:41Z","lastUpdateTime":"2020-11-08T15:29:41Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-11-08T15:28:15Z","lastUpdateTime":"2020-11-08T15:29:41Z","message":"ReplicaSet \"tensorboard-5f685f9d79\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2020-11-10T00:48:48Z"
  generation: 1
  labels:
    app: tensorboard
    kustomize.component: tensorboard
  name: tensorboard
  namespace: kubeflow
  resourceVersion: "408873"
  selfLink: /apis/apps/v1/namespaces/kubeflow/deployments/tensorboard
  uid: 81bb38e1-b7cd-4707-9302-48b168ecdd08
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      kustomize.component: tensorboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tensorboard
        kustomize.component: tensorboard
    spec:
      containers:
      - args:
        - --logdir=logs
        - --port=6006
        command:
        - /usr/local/bin/tensorboard
        image: tensorflow/tensorflow:1.8.0
        imagePullPolicy: IfNotPresent
        name: tensorboard
        ports:
        - containerPort: 6006
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-11-10T00:48:48Z"
    lastUpdateTime: "2020-11-10T00:48:53Z"
    message: ReplicaSet "tensorboard-6549cd78c9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-11-10T01:10:11Z"
    lastUpdateTime: "2020-11-10T01:10:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
