apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"admission-webhook","app.kubernetes.io/component":"poddefaults","app.kubernetes.io/name":"poddefaults","kustomize.component":"admission-webhook"},"name":"admission-webhook-deployment","namespace":"kubeflow"},"spec":{"selector":{"matchLabels":{"app":"admission-webhook","app.kubernetes.io/component":"poddefaults","app.kubernetes.io/name":"poddefaults","kustomize.component":"admission-webhook"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"labels":{"app":"admission-webhook","app.kubernetes.io/component":"poddefaults","app.kubernetes.io/name":"poddefaults","kustomize.component":"admission-webhook"}},"spec":{"containers":[{"args":["--tlsCertFile=/etc/webhook/certs/tls.crt","--tlsKeyFile=/etc/webhook/certs/tls.key"],"image":"gcr.io/kubeflow-images-public/admission-webhook:vmaster-ge5452b6f","name":"admission-webhook","volumeMounts":[{"mountPath":"/etc/webhook/certs","name":"webhook-cert","readOnly":true}]}],"serviceAccountName":"admission-webhook-service-account","volumes":[{"name":"webhook-cert","secret":{"secretName":"webhook-certs"}}]}}}}
  creationTimestamp: "2020-11-21T11:34:55Z"
  generation: 1
  labels:
    app: admission-webhook
    app.kubernetes.io/component: poddefaults
    app.kubernetes.io/name: poddefaults
    kustomize.component: admission-webhook
  name: admission-webhook-deployment
  namespace: kubeflow
  resourceVersion: "1152932"
  selfLink: /apis/apps/v1/namespaces/kubeflow/deployments/admission-webhook-deployment
  uid: b90928ab-99c6-4475-b128-33eea91edea3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: admission-webhook
      app.kubernetes.io/component: poddefaults
      app.kubernetes.io/name: poddefaults
      kustomize.component: admission-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: admission-webhook
        app.kubernetes.io/component: poddefaults
        app.kubernetes.io/name: poddefaults
        kustomize.component: admission-webhook
    spec:
      containers:
      - args:
        - --tlsCertFile=/etc/webhook/certs/tls.crt
        - --tlsKeyFile=/etc/webhook/certs/tls.key
        image: gcr.io/kubeflow-images-public/admission-webhook:vmaster-ge5452b6f
        imagePullPolicy: IfNotPresent
        name: admission-webhook
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/webhook/certs
          name: webhook-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      #restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: admission-webhook-service-account
      serviceAccountName: admission-webhook-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: webhook-certs
status:
  conditions:
  - lastTransitionTime: "2020-11-21T11:34:55Z"
    lastUpdateTime: "2020-11-21T11:36:17Z"
    message: ReplicaSet "admission-webhook-deployment-5bc67cb78" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-11-21T11:36:18Z"
    lastUpdateTime: "2020-11-21T11:36:18Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
