rbac:
  enabled: true

resources:
  requests:
    cpu: 0.2
    memory: 100Mi

cors: &cors
  allowOrigin: '*'

service:
  type: ClusterIP

config:
  BinderHub:
    #hub_url: https://binder.jupyteronline.com
    use_registry: true
    image_prefix: alphatics/binder-prod-
    hub_url: https://www.jupyteronline.com
    log_level: 10
