apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: www
  name: www
  labels:
    app: www
spec:
  selector:
    matchLabels:
      app: www
  strategy:
    type: Recreate
  replicas: 3
  template:
    metadata:
      labels:
        app: www
    spec:
            #      nodeName: 183.111.230.163
      containers:
      - name: flask-web-container
        image: binderhubonline/flask-www:1.0.8
        imagePullPolicy: Always
        #command: [ /usr/local/bin/gunicorn -c "python:config.gunicorn" --reload "hms.app:create_app()" ]
        #args:
        #- gunicorn
        #- -c
        #- python:config.gunicorn
        #- --reload
        #- hms.app:create_app()
        ports:
        - containerPort: 5000
        resources: {}
        #volumeMounts:
        #- name: webapp-code
        #  mountPath: /hms/hms
        #- name: webapp-config
        #  mountPath: /hms/config
      restartPolicy: Always
      #volumes:
      #- name: webapp-code
      #  hostPath:
      #    path: /home/alpha/projects/7_flask-web/hms
      #- name: webapp-config
      #  hostPath:
      #    path: /home/alpha/projects/7_flask-web/config
