apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"metadata-writer","app.kubernetes.io/component":"ml-pipeline","app.kubernetes.io/name":"kubeflow-pipelines"},"name":"metadata-writer","namespace":"kubeflow"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"metadata-writer","app.kubernetes.io/component":"ml-pipeline","app.kubernetes.io/name":"kubeflow-pipelines"}},"template":{"metadata":{"labels":{"app":"metadata-writer","app.kubernetes.io/component":"ml-pipeline","app.kubernetes.io/name":"kubeflow-pipelines"}},"spec":{"containers":[{"env":[{"name":"NAMESPACE_TO_WATCH","value":""}],"image":"gcr.io/ml-pipeline/metadata-writer:1.0.0","name":"main"}],"serviceAccountName":"kubeflow-pipelines-metadata-writer"}}}}
  creationTimestamp: "2020-11-21T10:15:16Z"
  generation: 1
  labels:
    app: metadata-writer
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
  name: metadata-writer
  namespace: kubeflow
  resourceVersion: "1113385"
  selfLink: /apis/apps/v1/namespaces/kubeflow/deployments/metadata-writer
  uid: 7d899dd4-418e-4f74-a9ac-ac06f5914800
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: metadata-writer
      app.kubernetes.io/component: ml-pipeline
      app.kubernetes.io/name: kubeflow-pipelines
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: metadata-writer
        app.kubernetes.io/component: ml-pipeline
        app.kubernetes.io/name: kubeflow-pipelines
    spec:
      containers:
      - env:
        - name: NAMESPACE_TO_WATCH
        image: gcr.io/ml-pipeline/metadata-writer:1.0.0
        imagePullPolicy: IfNotPresent
        name: main
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      #restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kubeflow-pipelines-metadata-writer
      serviceAccountName: kubeflow-pipelines-metadata-writer
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-11-21T10:15:17Z"
    lastUpdateTime: "2020-11-21T10:15:35Z"
    message: ReplicaSet "metadata-writer-59d755696c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-11-21T10:26:54Z"
    lastUpdateTime: "2020-11-21T10:26:54Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
