service:
  type: ClusterIP
  labels: {}
  annotations:
    prometheus.io/scrape: 'true'

jupyterhub:
  cull:
    enabled: true
    timeout: 600
    every: 660
    maxAge: 21600
    users: False
  rbac:
    enabled: true
  proxy:
    secretToken: 53a338a0aee98f74c2b431cac2ff7cc0e59d52be13aeea07a0145750529e050e
    nginx:
      proxBodySize: 512m
  storage:
    capacity: 2G
  hub:
    #allowNamedServers: true
    #namedServerLimitPerUser: 10
    redirectToServer: false
    cookieSecret: "5eb53f6818f742d8c62b535f0a6df54880e7039be0a9ae255436d95f4c661c29"
    #extraEnv:
    #  OAUTH2_AUTHORIZE_URL: https://keycloak.jupyterbook.com/auth/realms/master/protocol/openid-connect/auth
    #  OAUTH2_TOKEN_URL: https://keycloak.jupyterbook.com/auth/realms/master/protocol/openid-connect/token
    #  OAUTH_CALLBACK_URL: https://hub.jupyterbook.com/hub/oauth_callback
    db:
      type: postgres
      upgrade: true
      password: "@postgres"
      url: "postgresql+psycopg2://jupyterhub@hub-postgres-postgresql/jupyterhub"
      pvc:
        storageClassName: nfs-client
    extraConfig: |-
      c.Spawner.cmd = ['jupyter-labhub']
      jupyterlab: |
        c.Authenticator.auto_login = True
      hub: |
        c.JupyterHub.tornado_settings = {
          'headers': {
            'Content-Security-Policy': "base-uri 'self'"
          },
        }
      hub_extra: |
        c.JupyterHub.redirect_to_server = False
      spawner: >-
        c.Spawner.args = ["--NotebookApp.tornado_settings={ \
          'headers':{                                    \
            'Content-Security-Policy': \"base-uri 'self' \", \
          }, \
        }"]
      myConfig:  |
        config = '/etc/jupyter/jupyter_notebook_config.py'
        c.KubeSpawner.pod_name_template = 'jupyter-{username}{servername}'

  auth:
    type: ldap
    ldap:
      server:
        address: ldap-openldap.auth.svc
      dn:
        templates:
          - 'uid={username},ou=People,dc=jupyteronline,dc=com'
  
  singleuser:
    defaultUrl: "/lab"
    image:
      name: elyra/nb2kg
      tag: dev
    storage:
      type: dynamic
      capacity: 1Gi
      dynamic:
        storageClass: nfs-client
      extraVolumes:
        - name: jupyterhub-shared
          persistentVolumeClaim:
            claimName: jupyterhub-shared-pvc
      extraVolumeMounts:
        - name: jupyterhub-shared
          mountPath: /home/jovyan/shared
    extraEnv:
      KERNEL_USERNAME: jovyan 
      KG_URL: egw.jupyterbook.com
      KG_HTTP_USER: jovyan
      KERNEL_USERNAME: jovyan
      KG_REQUEST_TIMEOUT: 60
  rbac:
    enabled: true
  debug:
    enabled: true
