apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sso
  name: apacheds
  labels:
    app: apacheds
spec:
  selector:
    matchLabels:
      app: apacheds
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: apacheds
    spec:
      containers:
      - name: apacheds
        image: "openmicroscopy/apacheds:0.6.0"
        envFrom:
        - secretRef:
            name: apacheds-secret-private
        ports:
        - containerPort: 10389
          name: ldap
          protocol: TCP
        - containerPort: 10636
          name: ldaps
          protocol: TCP
        volumeMounts:
        - name: apacheds-files
          mountPath: /var/lib/apacheds
          subPath: files
        - name: apacheds-ldif
          mountPath: /etc/apacheds/data.ldif
          readOnly: true
      volumes:
      - name: apacheds-files
        persistentVolumeClaim:
          claimName: apacheds-volume
      - name: apacheds-ldif
        configMap:
          name: apacheds-ldif
