apiVersion: v1
kind: Service
metadata:
  namespace: sso
  name: apacheds
  labels:
    app: apacheds
spec:
  ports:
  - name: apacheds-ldap
    port: 389
    protocol: TCP
    targetPort: 10389
  - name: apacheds-ldaps
    port: 636
    protocol: TCP
    targetPort: 10636
  selector:
    app: apacheds
  type: ClusterIP
status:
  loadBalancer: {}

